<?php

declare(strict_types=1);

// GERADO a partir de src/app/data/mock.ts - é a carga inicial do catálogo.
// Editar aqui não muda a loja: depois do primeiro seed, a fonte de verdade
// passa a ser a tabela `livros` (editável pelo painel do Gerente).

return [
    'categorias' => [
        ['nome' => 'Inteligência Artificial', 'slug' => 'inteligencia-artificial', 'descricao' => 'Machine Learning, Deep Learning, LLMs e IA Generativa', 'cor' => '#0ea5e9', 'imagem_url' => 'https://images.unsplash.com/photo-1579567761406-4684ee0c75b6?w=800'],
        ['nome' => 'Blockchain', 'slug' => 'blockchain', 'descricao' => 'Smart Contracts, DeFi, Web3 e Criptoativos', 'cor' => '#8b5cf6', 'imagem_url' => 'https://images.unsplash.com/photo-1639322537228-f710d846310a?w=800'],
        ['nome' => 'Cibersegurança', 'slug' => 'ciberseguranca', 'descricao' => 'Pentest, Defesa, Malware e Segurança Ofensiva', 'cor' => '#ef4444', 'imagem_url' => 'https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=800'],
        ['nome' => 'Criptografia', 'slug' => 'criptografia', 'descricao' => 'Algoritmos, Protocolos e Fundamentos Matemáticos', 'cor' => '#f59e0b', 'imagem_url' => 'https://images.unsplash.com/photo-1633265486064-086b219458ec?w=800'],
        ['nome' => 'Arquitetura de Software', 'slug' => 'arquitetura-de-software', 'descricao' => 'Microsserviços, Clean Architecture e Design Patterns', 'cor' => '#10b981', 'imagem_url' => 'https://images.unsplash.com/photo-1489875347897-49f64b51c1f8?w=800'],
    ],
    'livros' => [
        [
            'id' => 'ai-001',
            'titulo' => 'Fundamentos de Inteligência Artificial',
            'autor' => 'Dr. Rafael Moreira',
            'categoria' => 'Inteligência Artificial',
            'descricao' => 'Uma introdução abrangente aos conceitos fundamentais da Inteligência Artificial, cobrindo desde os princípios básicos até as aplicações modernas em machine learning e deep learning. Ideal para desenvolvedores que desejam ingressar na área de IA com uma base sólida e prática.',
            'preco_fisico' => 89.9,
            'preco_ebook' => 59.9,
            'peso_gramas' => 1070,
            'formatos' => 'Físico,E-book',
            'capa_url' => 'https://images.unsplash.com/photo-1579567761406-4684ee0c75b6?w=400&q=80',
            'cor_capa' => '#0369a1',
            'estoque' => 15,
            'paginas' => 420,
            'publicado_em' => '2025-03-15',
            'isbn' => '978-85-12345-01-1',
            'destaque' => 1,
            'mais_vendido' => 1,
            'lancamento' => 0,
            'avaliacao' => 4.8,
            'num_avaliacoes' => 247,
            'tags' => ['IA', 'Iniciante', 'Machine Learning'],
        ],
        [
            'id' => 'ai-002',
            'titulo' => 'Redes Neurais Profundas na Prática',
            'autor' => 'Dra. Camila Santos',
            'categoria' => 'Inteligência Artificial',
            'descricao' => 'Domine as redes neurais profundas com implementações práticas em PyTorch. Este livro aborda CNNs, RNNs, Transformers e técnicas avançadas de otimização, com projetos reais do mercado de trabalho.',
            'preco_fisico' => 124.9,
            'preco_ebook' => 89.9,
            'peso_gramas' => 1380,
            'formatos' => 'Físico,E-book',
            'capa_url' => 'https://images.unsplash.com/photo-1687843040524-ef6dc103b01e?w=400&q=80',
            'cor_capa' => '#1d4ed8',
            'estoque' => 8,
            'paginas' => 560,
            'publicado_em' => '2025-06-01',
            'isbn' => '978-85-12345-02-8',
            'destaque' => 1,
            'mais_vendido' => 1,
            'lancamento' => 0,
            'avaliacao' => 4.9,
            'num_avaliacoes' => 183,
            'tags' => ['Deep Learning', 'Redes Neurais', 'PyTorch'],
        ],
        [
            'id' => 'ai-003',
            'titulo' => 'Large Language Models: Arquitetura e Aplicações',
            'autor' => 'Prof. Lucas Fernandes',
            'categoria' => 'Inteligência Artificial',
            'descricao' => 'Um mergulho profundo nos Large Language Models: como funcionam internamente, como são treinados e como aplicá-los em soluções empresariais. Inclui capítulos sobre fine-tuning, RAG, prompt engineering e deploy em produção.',
            'preco_fisico' => null,
            'preco_ebook' => 99.9,
            'peso_gramas' => 0,
            'formatos' => 'E-book',
            'capa_url' => 'https://images.unsplash.com/photo-1714548529197-537c1f0b6aa7?w=400&q=80',
            'cor_capa' => '#4f46e5',
            'estoque' => 0,
            'paginas' => 490,
            'publicado_em' => '2025-08-20',
            'isbn' => '978-85-12345-03-5',
            'destaque' => 1,
            'mais_vendido' => 0,
            'lancamento' => 1,
            'avaliacao' => 4.7,
            'num_avaliacoes' => 92,
            'tags' => ['LLM', 'GPT', 'Transformers', 'IA Generativa'],
        ],
        [
            'id' => 'ai-004',
            'titulo' => 'Agentes de IA: Design e Implementação',
            'autor' => 'Dr. Rafael Moreira & Eng. Pedro Alves',
            'categoria' => 'Inteligência Artificial',
            'descricao' => 'Aprenda a construir agentes de IA autônomos capazes de planejar, executar e aprender com suas próprias ações. Aborda frameworks modernos como LangChain, CrewAI e AutoGen com exemplos aplicados.',
            'preco_fisico' => 139.9,
            'preco_ebook' => 99.9,
            'peso_gramas' => 990,
            'formatos' => 'Físico,E-book',
            'capa_url' => 'https://images.unsplash.com/photo-1757466762489-52fea38071ad?w=400&q=80',
            'cor_capa' => '#0891b2',
            'estoque' => 12,
            'paginas' => 380,
            'publicado_em' => '2026-01-10',
            'isbn' => '978-85-12345-04-2',
            'destaque' => 0,
            'mais_vendido' => 0,
            'lancamento' => 1,
            'avaliacao' => 4.6,
            'num_avaliacoes' => 54,
            'tags' => ['Agentes', 'IA Generativa', 'AutoGPT', 'LangChain'],
        ],
        [
            'id' => 'ai-005',
            'titulo' => 'Machine Learning com Python',
            'autor' => 'Dra. Camila Santos',
            'categoria' => 'Inteligência Artificial',
            'descricao' => 'O guia definitivo para machine learning prático com Python. Da regressão linear ao gradient boosting, passando por validação cruzada, feature engineering e deploy de modelos em produção com FastAPI.',
            'preco_fisico' => 99.9,
            'preco_ebook' => 69.9,
            'peso_gramas' => 1270,
            'formatos' => 'Físico,E-book',
            'capa_url' => 'https://images.unsplash.com/photo-1770486036751-e55247238964?w=400&q=80',
            'cor_capa' => '#0c4a6e',
            'estoque' => 20,
            'paginas' => 510,
            'publicado_em' => '2024-11-05',
            'isbn' => '978-85-12345-05-9',
            'destaque' => 0,
            'mais_vendido' => 1,
            'lancamento' => 0,
            'avaliacao' => 4.9,
            'num_avaliacoes' => 312,
            'tags' => ['Machine Learning', 'Python', 'Scikit-learn'],
        ],
        [
            'id' => 'ai-006',
            'titulo' => 'Visão Computacional com Deep Learning',
            'autor' => 'Eng. Tiago Ribeiro',
            'categoria' => 'Inteligência Artificial',
            'descricao' => 'Detecte objetos, segmente imagens e implante modelos de visão computacional em dispositivos edge. Abrange YOLO, ResNet, diffusion models e técnicas de augmentação para dados escassos.',
            'preco_fisico' => 119.9,
            'preco_ebook' => 84.9,
            'peso_gramas' => 1130,
            'formatos' => 'Físico,E-book',
            'capa_url' => 'https://images.unsplash.com/photo-1609704721979-17e6855d5cbe?w=400&q=80',
            'cor_capa' => '#1e3a5f',
            'estoque' => 6,
            'paginas' => 445,
            'publicado_em' => '2025-04-22',
            'isbn' => '978-85-12345-06-6',
            'destaque' => 1,
            'mais_vendido' => 0,
            'lancamento' => 0,
            'avaliacao' => 4.7,
            'num_avaliacoes' => 128,
            'tags' => ['Visão Computacional', 'CNN', 'YOLO', 'TensorFlow'],
        ],
        [
            'id' => 'bc-001',
            'titulo' => 'Blockchain: Fundamentos e Aplicações',
            'autor' => 'Eng. Marcelo Viana',
            'categoria' => 'Blockchain',
            'descricao' => 'Entenda a tecnologia que está transformando finanças, logística e governança. Da teoria criptográfica dos blocos à construção de DApps na Ethereum, com exemplos práticos e casos de uso reais.',
            'preco_fisico' => 94.9,
            'preco_ebook' => 64.9,
            'peso_gramas' => 940,
            'formatos' => 'Físico,E-book',
            'capa_url' => 'https://images.unsplash.com/photo-1639322537228-f710d846310a?w=400&q=80',
            'cor_capa' => '#6d28d9',
            'estoque' => 18,
            'paginas' => 360,
            'publicado_em' => '2025-01-20',
            'isbn' => '978-85-12345-07-3',
            'destaque' => 0,
            'mais_vendido' => 1,
            'lancamento' => 0,
            'avaliacao' => 4.6,
            'num_avaliacoes' => 189,
            'tags' => ['Blockchain', 'Bitcoin', 'Ethereum', 'Iniciante'],
        ],
        [
            'id' => 'bc-002',
            'titulo' => 'Smart Contracts com Solidity',
            'autor' => 'Dra. Ana Lima',
            'categoria' => 'Blockchain',
            'descricao' => 'Construa contratos inteligentes seguros e eficientes com Solidity. Inclui padrões de segurança, auditoria de contratos, integração com front-end via ethers.js e deploy em mainnet e testnets.',
            'preco_fisico' => 109.9,
            'preco_ebook' => 74.9,
            'peso_gramas' => 1050,
            'formatos' => 'Físico,E-book',
            'capa_url' => 'https://images.unsplash.com/photo-1666816943035-15c29931e975?w=400&q=80',
            'cor_capa' => '#5b21b6',
            'estoque' => 10,
            'paginas' => 410,
            'publicado_em' => '2025-05-12',
            'isbn' => '978-85-12345-08-0',
            'destaque' => 1,
            'mais_vendido' => 0,
            'lancamento' => 0,
            'avaliacao' => 4.8,
            'num_avaliacoes' => 143,
            'tags' => ['Solidity', 'Smart Contracts', 'Ethereum', 'Web3'],
        ],
        [
            'id' => 'bc-003',
            'titulo' => 'DeFi: Finanças Descentralizadas',
            'autor' => 'Eng. Marcelo Viana',
            'categoria' => 'Blockchain',
            'descricao' => 'O universo das finanças descentralizadas em profundidade: AMMs, protocolos de empréstimo, stablecoins algorítmicas, bridges e os riscos inerentes ao ecossistema DeFi. Análise técnica e econômica.',
            'preco_fisico' => null,
            'preco_ebook' => 84.9,
            'peso_gramas' => 0,
            'formatos' => 'E-book',
            'capa_url' => 'https://images.unsplash.com/photo-1621761191319-c6fb62004040?w=400&q=80',
            'cor_capa' => '#4c1d95',
            'estoque' => 0,
            'paginas' => 320,
            'publicado_em' => '2025-09-01',
            'isbn' => '978-85-12345-09-7',
            'destaque' => 0,
            'mais_vendido' => 0,
            'lancamento' => 1,
            'avaliacao' => 4.5,
            'num_avaliacoes' => 67,
            'tags' => ['DeFi', 'DEX', 'Yield Farming', 'Protocolos'],
        ],
        [
            'id' => 'bc-004',
            'titulo' => 'NFTs e a Economia Digital',
            'autor' => 'Dr. Bruno Costa',
            'categoria' => 'Blockchain',
            'descricao' => 'Compreenda o fenômeno dos tokens não-fungíveis: padrões ERC-721/1155, marketplaces, direitos autorais digitais e o futuro da propriedade na internet. Inclui guia para criar e vender sua própria coleção.',
            'preco_fisico' => null,
            'preco_ebook' => 79.9,
            'peso_gramas' => 0,
            'formatos' => 'E-book',
            'capa_url' => 'https://images.unsplash.com/photo-1640158615573-cd28feb1bf4e?w=400&q=80',
            'cor_capa' => '#7c3aed',
            'estoque' => 0,
            'paginas' => 280,
            'publicado_em' => '2024-10-15',
            'isbn' => '978-85-12345-10-3',
            'destaque' => 0,
            'mais_vendido' => 0,
            'lancamento' => 0,
            'avaliacao' => 4.3,
            'num_avaliacoes' => 98,
            'tags' => ['NFT', 'Metaverso', 'ERC-721', 'Mercado Digital'],
        ],
        [
            'id' => 'cs-001',
            'titulo' => 'Cibersegurança Ofensiva e Defensiva',
            'autor' => 'Maj. Ricardo Nunes',
            'categoria' => 'Cibersegurança',
            'descricao' => 'A dualidade da cibersegurança moderna: aprenda a pensar como o atacante para defender melhor. Abrange toda a kill chain, técnicas de evasão, resposta a incidentes e construção de SOC eficiente.',
            'preco_fisico' => 129.9,
            'preco_ebook' => 89.9,
            'peso_gramas' => 1430,
            'formatos' => 'Físico,E-book',
            'capa_url' => 'https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=400&q=80',
            'cor_capa' => '#991b1b',
            'estoque' => 9,
            'paginas' => 580,
            'publicado_em' => '2025-02-28',
            'isbn' => '978-85-12345-11-0',
            'destaque' => 1,
            'mais_vendido' => 1,
            'lancamento' => 0,
            'avaliacao' => 4.9,
            'num_avaliacoes' => 276,
            'tags' => ['Red Team', 'Blue Team', 'SOC', 'Defesa'],
        ],
        [
            'id' => 'cs-002',
            'titulo' => 'Pentest: Técnicas e Ferramentas',
            'autor' => 'Eng. Fernanda Rocha',
            'categoria' => 'Cibersegurança',
            'descricao' => 'Torne-se um pentester profissional com este guia completo sobre testes de invasão. Metodologias reconhecidas (PTES, OWASP), ferramentas essenciais, relatórios profissionais e preparação para certificações.',
            'preco_fisico' => 119.9,
            'preco_ebook' => 84.9,
            'peso_gramas' => 1290,
            'formatos' => 'Físico,E-book',
            'capa_url' => 'https://images.unsplash.com/photo-1618060932014-4deda4932554?w=400&q=80',
            'cor_capa' => '#7f1d1d',
            'estoque' => 14,
            'paginas' => 520,
            'publicado_em' => '2025-07-10',
            'isbn' => '978-85-12345-12-7',
            'destaque' => 0,
            'mais_vendido' => 0,
            'lancamento' => 1,
            'avaliacao' => 4.8,
            'num_avaliacoes' => 164,
            'tags' => ['Pentest', 'Kali Linux', 'Metasploit', 'OWASP'],
        ],
        [
            'id' => 'cs-003',
            'titulo' => 'Segurança em Aplicações Web',
            'autor' => 'Dra. Juliana Matos',
            'categoria' => 'Cibersegurança',
            'descricao' => 'Proteja suas aplicações web com práticas de DevSecOps: cobertura completa do OWASP Top 10, headers de segurança, autenticação robusta, gestão de sessões e integração de segurança no pipeline CI/CD.',
            'preco_fisico' => 104.9,
            'preco_ebook' => 74.9,
            'peso_gramas' => 1010,
            'formatos' => 'Físico,E-book',
            'capa_url' => 'https://images.unsplash.com/photo-1614064548237-096f735f344f?w=400&q=80',
            'cor_capa' => '#b91c1c',
            'estoque' => 22,
            'paginas' => 390,
            'publicado_em' => '2024-12-01',
            'isbn' => '978-85-12345-13-4',
            'destaque' => 0,
            'mais_vendido' => 1,
            'lancamento' => 0,
            'avaliacao' => 4.7,
            'num_avaliacoes' => 201,
            'tags' => ['OWASP', 'XSS', 'SQL Injection', 'DevSecOps'],
        ],
        [
            'id' => 'cs-004',
            'titulo' => 'Análise de Malware',
            'autor' => 'Maj. Ricardo Nunes',
            'categoria' => 'Cibersegurança',
            'descricao' => 'Disseque amostras de malware reais em laboratório seguro: análise estática e dinâmica, engenharia reversa com Ghidra e IDA, classificação de famílias de malware e geração de IoCs para defesa.',
            'preco_fisico' => 114.9,
            'preco_ebook' => 79.9,
            'peso_gramas' => 1160,
            'formatos' => 'Físico,E-book',
            'capa_url' => 'https://images.unsplash.com/photo-1740560051549-cc6799220d48?w=400&q=80',
            'cor_capa' => '#450a0a',
            'estoque' => 5,
            'paginas' => 460,
            'publicado_em' => '2026-02-15',
            'isbn' => '978-85-12345-14-1',
            'destaque' => 0,
            'mais_vendido' => 0,
            'lancamento' => 1,
            'avaliacao' => 4.8,
            'num_avaliacoes' => 42,
            'tags' => ['Malware', 'Engenharia Reversa', 'Threat Intelligence'],
        ],
        [
            'id' => 'cr-001',
            'titulo' => 'Criptografia Moderna: Teoria e Prática',
            'autor' => 'Prof. Henrique Luz',
            'categoria' => 'Criptografia',
            'descricao' => 'Da matemática à implementação: estude criptografia simétrica, assimétrica, funções de hash e protocolos de troca de chaves. Implementações práticas em Python com análise de segurança e ataques conhecidos.',
            'preco_fisico' => 99.9,
            'preco_ebook' => 69.9,
            'peso_gramas' => 1100,
            'formatos' => 'Físico,E-book',
            'capa_url' => 'https://images.unsplash.com/photo-1633265486064-086b219458ec?w=400&q=80',
            'cor_capa' => '#92400e',
            'estoque' => 11,
            'paginas' => 430,
            'publicado_em' => '2025-04-05',
            'isbn' => '978-85-12345-15-8',
            'destaque' => 1,
            'mais_vendido' => 1,
            'lancamento' => 0,
            'avaliacao' => 4.8,
            'num_avaliacoes' => 158,
            'tags' => ['Criptografia', 'AES', 'RSA', 'Hash'],
        ],
        [
            'id' => 'cr-002',
            'titulo' => 'Criptografia de Curvas Elípticas',
            'autor' => 'Prof. Henrique Luz',
            'categoria' => 'Criptografia',
            'descricao' => 'Matemática e implementação da criptografia baseada em curvas elípticas: ECDH, ECDSA, curvas NIST e Curve25519. Análise de segurança, resistência quântica e aplicações em blockchain e TLS.',
            'preco_fisico' => null,
            'preco_ebook' => 134.9,
            'peso_gramas' => 0,
            'formatos' => 'E-book',
            'capa_url' => 'https://images.unsplash.com/photo-1509966756634-9c23dd6e6815?w=400&q=80',
            'cor_capa' => '#78350f',
            'estoque' => 0,
            'paginas' => 380,
            'publicado_em' => '2025-11-20',
            'isbn' => '978-85-12345-16-5',
            'destaque' => 0,
            'mais_vendido' => 0,
            'lancamento' => 1,
            'avaliacao' => 4.9,
            'num_avaliacoes' => 38,
            'tags' => ['ECC', 'Curvas Elípticas', 'ECDSA', 'Avançado'],
        ],
        [
            'id' => 'cr-003',
            'titulo' => 'Protocolos Criptográficos Avançados',
            'autor' => 'Dra. Beatriz Campos',
            'categoria' => 'Criptografia',
            'descricao' => 'Estude os protocolos que sustentam a segurança da internet: TLS 1.3, provas de conhecimento-zero, computação multi-party e criptografia homomórfica. Implementações práticas e análise formal de segurança.',
            'preco_fisico' => 124.9,
            'preco_ebook' => 89.9,
            'peso_gramas' => 1250,
            'formatos' => 'Físico,E-book',
            'capa_url' => 'https://images.unsplash.com/photo-1599837565318-67429bde7162?w=400&q=80',
            'cor_capa' => '#d97706',
            'estoque' => 7,
            'paginas' => 500,
            'publicado_em' => '2026-03-01',
            'isbn' => '978-85-12345-17-2',
            'destaque' => 0,
            'mais_vendido' => 0,
            'lancamento' => 1,
            'avaliacao' => 4.7,
            'num_avaliacoes' => 29,
            'tags' => ['TLS', 'Zero-Knowledge', 'MPC', 'Protocolos'],
        ],
        [
            'id' => 'sw-001',
            'titulo' => 'Arquitetura de Microsserviços com IA',
            'autor' => 'Arq. Rodrigo Mello',
            'categoria' => 'Arquitetura de Software',
            'descricao' => 'Projete sistemas distribuídos modernos integrando componentes de IA de forma resiliente. Padrões de arquitetura para MLOps, service mesh, event-driven e observabilidade em produção com exemplos reais.',
            'preco_fisico' => 109.9,
            'preco_ebook' => 79.9,
            'peso_gramas' => 1180,
            'formatos' => 'Físico,E-book',
            'capa_url' => 'https://images.unsplash.com/photo-1489875347897-49f64b51c1f8?w=400&q=80',
            'cor_capa' => '#065f46',
            'estoque' => 13,
            'paginas' => 470,
            'publicado_em' => '2025-05-30',
            'isbn' => '978-85-12345-18-9',
            'destaque' => 1,
            'mais_vendido' => 1,
            'lancamento' => 0,
            'avaliacao' => 4.8,
            'num_avaliacoes' => 197,
            'tags' => ['Microsserviços', 'Docker', 'Kubernetes', 'MLOps'],
        ],
        [
            'id' => 'sw-002',
            'titulo' => 'Clean Architecture na Era da IA',
            'autor' => 'Arq. Rodrigo Mello',
            'categoria' => 'Arquitetura de Software',
            'descricao' => 'Aplique os princípios de Clean Architecture e DDD em sistemas que incorporam modelos de IA. Estratégias para manter código limpo, testável e evolutivo mesmo com a complexidade de componentes inteligentes.',
            'preco_fisico' => 119.9,
            'preco_ebook' => 84.9,
            'peso_gramas' => 1020,
            'formatos' => 'Físico,E-book',
            'capa_url' => 'https://images.unsplash.com/photo-1692106979244-a2ac98253f6b?w=400&q=80',
            'cor_capa' => '#047857',
            'estoque' => 16,
            'paginas' => 395,
            'publicado_em' => '2025-08-10',
            'isbn' => '978-85-12345-19-6',
            'destaque' => 0,
            'mais_vendido' => 0,
            'lancamento' => 1,
            'avaliacao' => 4.7,
            'num_avaliacoes' => 112,
            'tags' => ['Clean Architecture', 'SOLID', 'DDD', 'Testabilidade'],
        ],
        [
            'id' => 'sw-003',
            'titulo' => 'Design Patterns para Sistemas Inteligentes',
            'autor' => 'Dra. Sofia Carvalho',
            'categoria' => 'Arquitetura de Software',
            'descricao' => 'Adapte e aplique padrões de projeto clássicos e emergentes em sistemas com componentes de IA: observer para eventos de modelo, strategy para troca de algoritmos, factory para criação de agentes e muito mais.',
            'preco_fisico' => 94.9,
            'preco_ebook' => 64.9,
            'peso_gramas' => 900,
            'formatos' => 'Físico,E-book',
            'capa_url' => 'https://images.unsplash.com/photo-1599837487527-e009248aa71b?w=400&q=80',
            'cor_capa' => '#064e3b',
            'estoque' => 19,
            'paginas' => 340,
            'publicado_em' => '2024-09-15',
            'isbn' => '978-85-12345-20-2',
            'destaque' => 0,
            'mais_vendido' => 1,
            'lancamento' => 0,
            'avaliacao' => 4.6,
            'num_avaliacoes' => 234,
            'tags' => ['Design Patterns', 'GoF', 'IA', 'Refatoração'],
        ],
        [
            'id' => 'kit-001',
            'titulo' => 'Kit Completo: Trilha de IA',
            'autor' => 'Vários Autores',
            'categoria' => 'Inteligência Artificial',
            'descricao' => 'A trilha completa para se tornar um especialista em IA: inclui os 3 livros mais vendidos da COMPIA (Fundamentos de IA + Redes Neurais Profundas + Machine Learning com Python). Desconto especial no kit.',
            'preco_fisico' => 249.9,
            'preco_ebook' => null,
            'peso_gramas' => 3720,
            'formatos' => 'Kit',
            'capa_url' => 'https://images.unsplash.com/photo-1579567761406-4684ee0c75b6?w=400&q=80',
            'cor_capa' => '#1e40af',
            'estoque' => 8,
            'paginas' => 0,
            'publicado_em' => '2025-01-01',
            'isbn' => '978-85-12345-KIT-1',
            'destaque' => 1,
            'mais_vendido' => 0,
            'lancamento' => 0,
            'avaliacao' => 4.9,
            'num_avaliacoes' => 89,
            'tags' => ['Kit', 'IA', 'Machine Learning', 'Deep Learning', 'Completo'],
        ],
    ],
];
